version: '3.8'
 
services:
  # Book Catalog Service
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://part3sai_user:kRsm3qhmjWII4ePaNr6QFsudxIWcIK8S@dpg-crkfbl0gph6c73c9afe0-a.oregon-postgres.render.com/part3sai
 
  # Inventory Management Service
  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://part3sai_user:kRsm3qhmjWII4ePaNr6QFsudxIWcIK8S@dpg-crkfbl0gph6c73c9afe0-a.oregon-postgres.render.com/part3sai