apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sravella.azurecr.io/book_catalog
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: "postgresql://part3sai_user:kRsm3qhmjWII4ePaNr6QFsudxIWcIK8S@dpg-crkfbl0gph6c73c9afe0-a.oregon-postgres.render.com/part3sai"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: book-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: sravella.azurecr.io/inventory_management
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: "postgresql://part3sai_user:kRsm3qhmjWII4ePaNr6QFsudxIWcIK8S@dpg-crkfbl0gph6c73c9afe0-a.oregon-postgres.render.com/part3sai"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  selector:
    app: inventory-management